# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-12 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0006_auto_20170912_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
