# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-12 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0008_auto_20170912_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='photo',
            field=models.FileField(upload_to='gigs'),
        ),
    ]
